services:
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./BackendAPI
    ports:
      - "5074:5074"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TESTQLK;Username=postgres;Password=postgres
      - ConnectionStrings__HangfireConnection=Host=db;Port=5432;Database=TESTQLK;Username=postgres;Password=postgres
      - Hangfire__Enabled=true
      - Redis__ConnectionString=redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TESTQLK
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data: