// <auto-generated />
using System;
using BackendAPI.BE.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageItem", b =>
                {
                    b.Property<int>("DamageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DamageItemId"));

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DamageItemId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("damageItems");

                    b.HasData(
                        new
                        {
                            DamageItemId = 1,
                            NoteId = 3,
                            ProductId = 2,
                            Quantity = 1,
                            Reason = "Broken"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryItem", b =>
                {
                    b.Property<int>("DeliveryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryItemId"));

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryItemId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("deliveryItems");

                    b.HasData(
                        new
                        {
                            DeliveryItemId = 1,
                            NoteId = 2,
                            ProductId = 1,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.InfractionTicket", b =>
                {
                    b.Property<int>("InfractionTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InfractionTicketId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("InfractionTicketId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InfractionTickets");

                    b.HasData(
                        new
                        {
                            InfractionTicketId = 1,
                            Date = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Late to shift",
                            Penalty = 50000m,
                            UserId = 2,
                            WarehouseId = 1
                        },
                        new
                        {
                            InfractionTicketId = 2,
                            Date = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Missing checklist",
                            Penalty = 30000m,
                            UserId = 1,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("InvitationId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("WarehouseId", "InvitedUserId")
                        .IsUnique();

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            InvitationId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvitedUserId = 3,
                            InviterUserId = 1,
                            Role = "STAFF",
                            Status = "PENDING",
                            WarehouseId = 1
                        },
                        new
                        {
                            InvitationId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvitedUserId = 1,
                            InviterUserId = 2,
                            Role = "MANAGER",
                            Status = "APPROVED",
                            WarehouseId = 2
                        },
                        new
                        {
                            InvitationId = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvitedUserId = 3,
                            InviterUserId = 2,
                            Role = "STAFF",
                            Status = "REJECTED",
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Notes");

                    b.HasDiscriminator<string>("NoteType").HasValue("Note");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.OTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Code");

                    b.ToTable("OTPs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "123456",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@test.com",
                            Expiration = new DateTime(2026, 1, 12, 0, 10, 0, 0, DateTimeKind.Utc),
                            IsUsed = false
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gest@test.com",
                            Expiration = new DateTime(2026, 1, 13, 1, 0, 0, 0, DateTimeKind.Utc),
                            Token = "password-reset-token-1"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionCode = "NOTE_APPROVE"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionCode = "NOTE_REJECT"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionCode = "NOTE_VIEW_ALL"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionCode = "STAFF_MANAGE"
                        },
                        new
                        {
                            PermissionId = 5,
                            PermissionCode = "INFRACTION_MANAGE"
                        },
                        new
                        {
                            PermissionId = 6,
                            PermissionCode = "WAREHOUSE_MANAGE"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionCode = "PRODUCT_ADD"
                        },
                        new
                        {
                            PermissionId = 8,
                            PermissionCode = "PRODUCT_DELETE"
                        },
                        new
                        {
                            PermissionId = 9,
                            PermissionCode = "SUPPLIER_MANAGE"
                        },
                        new
                        {
                            PermissionId = 10,
                            PermissionCode = "SHIFT_MANAGE"
                        },
                        new
                        {
                            PermissionId = 11,
                            PermissionCode = "INVITATION_MANAGE"
                        },
                        new
                        {
                            PermissionId = 12,
                            PermissionCode = "NOTE_CREATE"
                        },
                        new
                        {
                            PermissionId = 13,
                            PermissionCode = "NOTE_EDIT"
                        },
                        new
                        {
                            PermissionId = 14,
                            PermissionCode = "PRODUCT_VIEW"
                        },
                        new
                        {
                            PermissionId = 15,
                            PermissionCode = "SUPPLIER_VIEW"
                        },
                        new
                        {
                            PermissionId = 16,
                            PermissionCode = "SHIFT_VIEW"
                        },
                        new
                        {
                            PermissionId = 17,
                            PermissionCode = "INFRACTION_VIEW"
                        },
                        new
                        {
                            PermissionId = 18,
                            PermissionCode = "STAFF_VIEW"
                        },
                        new
                        {
                            PermissionId = 19,
                            PermissionCode = "NOTE_VIEW_OWN"
                        },
                        new
                        {
                            PermissionId = 20,
                            PermissionCode = "WAREHOUSE_VIEW"
                        },
                        new
                        {
                            PermissionId = 21,
                            PermissionCode = "INVITATION_VIEW"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Category A",
                            DamagedQuantity = 1,
                            DefectiveQuantity = 2,
                            Description = "Sample product 1",
                            Name = "Product 1",
                            SellPrice = 100000m,
                            StockQuantity = 100,
                            WarehouseId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Category B",
                            DamagedQuantity = 0,
                            DefectiveQuantity = 1,
                            Description = "Sample product 2",
                            Name = "Product 2",
                            SellPrice = 200000m,
                            StockQuantity = 50,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ProductSupplier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductSuppliers");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            SupplierId = 1,
                            Price = 90000m
                        },
                        new
                        {
                            ProductId = 2,
                            SupplierId = 2,
                            Price = 180000m
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ReceiptItem", b =>
                {
                    b.Property<int>("ReceiptItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceiptItemId"));

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ReceiptItemId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("receiptItems");

                    b.HasData(
                        new
                        {
                            ReceiptItemId = 1,
                            NoteId = 1,
                            ProductId = 1,
                            Quantity = 60
                        },
                        new
                        {
                            ReceiptItemId = 2,
                            NoteId = 1,
                            ProductId = 1,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiresAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "refresh-token-1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpiresAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "refresh-token-2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "OWNER"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "MANAGER"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "STAFF"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("ShiftId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            Duty = "Receive goods",
                            EndTime = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Morning shift",
                            StartTime = new DateTime(2026, 1, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            WarehouseId = 1
                        },
                        new
                        {
                            ShiftId = 2,
                            Duty = "Inventory check",
                            EndTime = new DateTime(2026, 1, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Regular shift",
                            StartTime = new DateTime(2026, 1, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Name = "Supplier 1",
                            WarehouseId = 1,
                            email = "supplier1@test.com",
                            phone = "0900000001"
                        },
                        new
                        {
                            SupplierId = 2,
                            Name = "Supplier 2",
                            WarehouseId = 2,
                            email = "supplier2@test.com",
                            phone = "0900000002"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.TestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sample item 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sample item 2"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Main St, City, Country",
                            Dob = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@test.com",
                            FullName = "Manager kho1, staff kho 2",
                            IsVerified = true,
                            PasswordHash = "$2a$10$7EqJtq98hPqEX7fNZaFWo.ES8wEaUfw4ptxtzfPv.UELALxjFaRai",
                            Phone = "0123456789"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Oak Ave, City, Country",
                            Dob = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@test.com",
                            FullName = "Staff kho1, Manager kho 2",
                            IsVerified = false,
                            PasswordHash = "$2a$10$7EqJtq98hPqEX7fNZaFWo.ES8wEaUfw4ptxtzfPv.UELALxjFaRai",
                            Phone = "0123456789"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Pine Rd, City, Country",
                            Dob = new DateTime(2000, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gest@test.com",
                            FullName = "Gest",
                            IsVerified = false,
                            PasswordHash = "$2a$10$7EqJtq98hPqEX7fNZaFWo.ES8wEaUfw4ptxtzfPv.UELALxjFaRai",
                            Phone = "0123456789"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.VerifyEmailToken", b =>
                {
                    b.Property<int>("VerifyEmailTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerifyEmailTokenId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("VerifyEmailTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VerifyEmailTokens");

                    b.HasData(
                        new
                        {
                            VerifyEmailTokenId = 1,
                            Email = "manager@test.com",
                            ExpiresAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "verify-email-token-1",
                            UserId = 1
                        },
                        new
                        {
                            VerifyEmailTokenId = 2,
                            Email = "staff@test.com",
                            ExpiresAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "verify-email-token-2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WarehouseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("urlimage")
                        .HasColumnType("text");

                    b.HasKey("WarehouseId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            Location = "Ho Chi Minh City",
                            Name = "Warehouse 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            WarehouseId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 2,
                            Location = "Ha Noi",
                            Name = "Warehouse 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.WarehouseStaff", b =>
                {
                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("WarehouseId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("WarehouseStaffs");

                    b.HasData(
                        new
                        {
                            WarehouseId = 1,
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            WarehouseId = 1,
                            UserId = 2,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageNote", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DamageNote");

                    b.HasData(
                        new
                        {
                            NoteId = 3,
                            Date = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "REJECTED",
                            UserId = 2,
                            WarehouseId = 2,
                            type = "DamageNote",
                            Description = "Damaged packaging"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryNote", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DeliveryNote");

                    b.HasData(
                        new
                        {
                            NoteId = 2,
                            Date = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PENDING",
                            UserId = 2,
                            WarehouseId = 1,
                            type = "DeliveryNote",
                            Destination = "Store A"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("qualityCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SupplierId");

                    b.HasDiscriminator().HasValue("GoodsReceipt");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Date = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "APPROVED",
                            UserId = 1,
                            WarehouseId = 1,
                            type = "GoodsReceipt",
                            DefectiveQuantity = 2,
                            StockQuantity = 100,
                            SupplierId = 1,
                            qualityCheckStatus = "PASSED"
                        });
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.DamageNote", "DamageNote")
                        .WithMany("DamageItems")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("DamageItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DamageNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.DeliveryNote", "DeliveryNote")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.InfractionTicket", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("InfractionTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("InfractionTickets")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Invitation", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("Invitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("Invitations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Note", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", null)
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Product", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ProductSupplier", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ReceiptItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.GoodsReceipt", "GoodReceipt")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Shift", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("Shifts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Supplier", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("Suppliers")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.VerifyEmailToken", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("VerifyEmailTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Warehouse", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.WarehouseStaff", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Role", "Role")
                        .WithMany("WarehouseStaffs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithMany("WarehouseStaffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("WarehouseStaffs")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Product", b =>
                {
                    b.Navigation("DamageItems");

                    b.Navigation("DeliveryItems");

                    b.Navigation("ProductSuppliers");

                    b.Navigation("ReceiptItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("WarehouseStaffs");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.User", b =>
                {
                    b.Navigation("InfractionTickets");

                    b.Navigation("Invitations");

                    b.Navigation("Notes");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Shifts");

                    b.Navigation("VerifyEmailTokens");

                    b.Navigation("WarehouseStaffs");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Warehouse", b =>
                {
                    b.Navigation("InfractionTickets");

                    b.Navigation("Invitations");

                    b.Navigation("Products");

                    b.Navigation("Shifts");

                    b.Navigation("Suppliers");

                    b.Navigation("WarehouseStaffs");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageNote", b =>
                {
                    b.Navigation("DamageItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryNote", b =>
                {
                    b.Navigation("DeliveryItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("ReceiptItems");
                });
#pragma warning restore 612, 618
        }
    }
}
