// <auto-generated />
using System;
using BackendAPI.BE.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPI.BE.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321092603_RemoveRoleFromUsers")]
    partial class RemoveRoleFromUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageItem", b =>
                {
                    b.Property<string>("DamageItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DamageItemId");

                    b.HasIndex("NoteID");

                    b.HasIndex("ProductId");

                    b.ToTable("damageItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryItem", b =>
                {
                    b.Property<string>("DeliveryItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DeliveryItemId");

                    b.HasIndex("NoteID");

                    b.HasIndex("ProductId");

                    b.ToTable("deliveryItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.InfractionTicket", b =>
                {
                    b.Property<string>("InfractionTicketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InfractionTicketId");

                    b.HasIndex("StaffId");

                    b.ToTable("InfractionTickets");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Note", b =>
                {
                    b.Property<string>("NoteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StaffUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("Notes");

                    b.HasDiscriminator<string>("NoteType").HasValue("Note");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ProductSupplier", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductSuppliers");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ReceiptItem", b =>
                {
                    b.Property<string>("ReceiptItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ReceiptItemId");

                    b.HasIndex("NoteID");

                    b.HasIndex("ProductId");

                    b.ToTable("receiptItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Shift", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.HasIndex("StaffId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Staff", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Supplier", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.TestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageNote", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DamageNote");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryNote", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DeliveryNote");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.HasBaseType("BackendAPI.BE.DAL.Entities.Note");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("qualityCheckStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("SupplierId");

                    b.HasDiscriminator().HasValue("GoodsReceipt");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.DamageNote", "DamageNote")
                        .WithMany("DamageItems")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("DamageItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.DeliveryNote", "DeliveryNote")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.InfractionTicket", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Staff", "Staff")
                        .WithMany("InfractionTickets")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Note", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Staff", "Staff")
                        .WithMany("Notes")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ProductSupplier", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.ReceiptItem", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.GoodsReceipt", "GoodReceipt")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.BE.DAL.Entities.Product", "Product")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Shift", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Staff", "Staff")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Staff", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("BackendAPI.BE.DAL.Entities.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("BackendAPI.BE.DAL.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Product", b =>
                {
                    b.Navigation("DamageItems");

                    b.Navigation("DeliveryItems");

                    b.Navigation("ProductSuppliers");

                    b.Navigation("ReceiptItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Staff", b =>
                {
                    b.Navigation("InfractionTickets");

                    b.Navigation("Notes");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DamageNote", b =>
                {
                    b.Navigation("DamageItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.DeliveryNote", b =>
                {
                    b.Navigation("DeliveryItems");
                });

            modelBuilder.Entity("BackendAPI.BE.DAL.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("ReceiptItems");
                });
#pragma warning restore 612, 618
        }
    }
}
