name: CI Pipeline (Test & Sync)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json
      - name: Clean npm cache
        run: npm cache clean --force    
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci
      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
      - name: Restore dependencies
        working-directory: ./BackendAPI
        run: dotnet restore
      - name: Build Backend
        working-directory: ./BackendAPI
        run: dotnet build --configuration Release --no-restore

  sync-to-deploy:
    needs: [build-frontend, build-backend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_DEPLOY }}
          fetch-depth: 0
      - name: Push changes to deploy branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout deploy || git checkout -b deploy
          git merge main
          git push origin deploy
